language: ruby
rvm:
  - 2.4.1

install: gem install html-proofer

script: htmlproofer home.html --url-ignore "#"

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
  - test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: true # route your build to the container-based infrastructure for a faster build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: alyssasgable@gmail.com

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "innovateafitc.test"
  skip_cleanup: true
  acl: public_read
  local_dir: public

exclude: [vendor]
